### ISSUE TITLE
Lenovo Yoga Book Support

### ISSUE THREAD

**Issue by Ligh7C** [sriharshaarangi/BatteryChargeLimit#97]
Hi All,

I would like to get support for the Lenovo Yoga Book (YB1-X90F) in this app. I found the necessary files on my rooted Yoga Book but I'm having trouble getting my test edits to the files to stick. Any idea what I could be doing wrong?

The files are located here on this device:
/sys/class/power_supply/usb-main/enable_charging
/sys/class/power_supply/usb-main/enable_charger

I chmoded both files and was able to echo 0 to each file but when I echo the file again, it seems to still show 1 despite the echo command completing successfully. 

Screenshots below:
https://imgur.com/a/JAneX
https://imgur.com/a/YKwY6

Thanks in advance for any help.
Ligh7C

**Comment by milux** [comment]
I have to agree that the file names look promising.
However, you did everything right and still it doesn't show any effect. Therefore, adding any of those files to BCL will not help anyone a bit, because BCL does exactly the same thing.
So, I think you have to go on searching your file system, sorry. 😞
